In [1]:
# Importing Libraries
import pandas as pd 
import numpy as np 

# Data visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
# load Feature Values
values=pd.read_csv("values.csv")

# load Target Labels
labels=pd.read_csv("labels.csv")

In [3]:
values.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,0z64un,1,normal,128,2,0,0,2,308,0.0,1,45,170,0
1,ryoo3j,2,normal,110,3,0,0,0,214,1.6,0,54,158,0
2,yt1s1x,1,normal,125,4,3,0,2,304,0.0,1,77,162,1
3,l2xjde,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0
4,oyt4ek,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0

In [4]:
labels.head()

  patient_id  heart_disease_present
0     0z64un                      0
1     ryoo3j                      0
2     yt1s1x                      1
3     l2xjde                      1
4     oyt4ek                      0

In [5]:
values.shape

(180, 14)

In [6]:
labels.shape

(180, 2)

In [7]:
# Both values and labels have common columns patient id and heart disease present we will merge both datasets
# Merge values and Labels on patient's id
df=pd.merge(values,labels, on='patient_id')
df.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina,heart_disease_present
0,0z64un,1,normal,128,2,0,0,2,308,0.0,1,45,170,0,0
1,ryoo3j,2,normal,110,3,0,0,0,214,1.6,0,54,158,0,0
2,yt1s1x,1,normal,125,4,3,0,2,304,0.0,1,77,162,1,1
3,l2xjde,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0,1
4,oyt4ek,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0,0

In [8]:
df.shape

(180, 15)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   patient_id                            180 non-null    object
 1   slope_of_peak_exercise_st_segment     180 non-null    int64
 2   thal                                  180 non-null    object
 3   resting_blood_pressure                180 non-null    int64
 4   chest_pain_type                       180 non-null    int64
 5   num_major_vessels                     180 non-null    int64
 6   fasting_blood_sugar_gt_120_mg_per_dl  180 non-null    int64
 7   resting_ekg_results                   180 non-null    int64
 8   serum_cholesterol_mg_per_dl           180 non-null    int64
 9   oldpeak_eq_st_depression              180 non-null    float64
 10  sex                                   180 non-null    int64
 11  age                                   180 non-null    int64
 12  max_heart_rate_achieved               180 non-null    int64
 13  exercise_induced_angina               180 non-null    int64
 14  heart_disease_present                 180 non-null    int64
dtypes: float64(1), int64(12), object(2)
memory usage: 21.2+ KB

In [10]:
df.describe()

,slope_of_peak_exercise_st_segment,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina,heart_disease_present
count,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000
mean,1.550000,131.311111,3.155556,0.694444,0.161111,1.050000,249.211111,1.010000,0.688889,54.811111,149.483333,0.316667,0.444444
std,0.618838,17.010443,0.938454,0.969347,0.368659,0.998742,52.717969,1.121357,0.464239,9.334737,22.063513,0.466474,0.498290
min,1.000000,94.000000,1.000000,0.000000,0.000000,0.000000,126.000000,0.000000,0.000000,29.000000,96.000000,0.000000,0.000000
25%,1.000000,120.000000,3.000000,0.000000,0.000000,0.000000,213.750000,0.000000,0.000000,48.000000,132.000000,0.000000,0.000000
50%,1.000000,130.000000,3.000000,0.000000,0.000000,2.000000,245.500000,0.800000,1.000000,55.000000,152.000000,0.000000,0.000000
75%,2.000000,140.000000,4.000000,1.000000,0.000000,2.000000,281.250000,1.600000,1.000000,62.000000,166.250000,1.000000,1.000000
max,3.000000,180.000000,4.000000,3.000000,1.000000,2.000000,564.000000,6.200000,1.000000,77.000000,202.000000,1.000000,1.000000

In [11]:
df.columns

Index(['patient_id', 'slope_of_peak_exercise_st_segment', 'thal',
       'resting_blood_pressure', 'chest_pain_type', 'num_major_vessels',
       'fasting_blood_sugar_gt_120_mg_per_dl', 'resting_ekg_results',
       'serum_cholesterol_mg_per_dl', 'oldpeak_eq_st_depression', 'sex', 'age',
       'max_heart_rate_achieved', 'exercise_induced_angina',
       'heart_disease_present'],
      dtype='object')

In [12]:
# Exploratory Data Analysis
# Checking the target variable distribution
# Count number of patient's in each class
df['heart_disease_present'].value_counts()

heart_disease_present
0    100
1     80
Name: count, dtype: int64

In [13]:
# Percentage distribusion
df['heart_disease_present'].value_counts(normalize=True)*100

heart_disease_present
0    55.555556
1    44.444444
Name: proportion, dtype: float64

In [14]:
# Checking the duplicates
df.duplicated().sum()

0

In [15]:
df.isnull().sum()

patient_id                              0
slope_of_peak_exercise_st_segment       0
thal                                    0
resting_blood_pressure                  0
chest_pain_type                         0
num_major_vessels                       0
fasting_blood_sugar_gt_120_mg_per_dl    0
resting_ekg_results                     0
serum_cholesterol_mg_per_dl             0
oldpeak_eq_st_depression                0
sex                                     0
age                                     0
max_heart_rate_achieved                 0
exercise_induced_angina                 0
heart_disease_present                   0
dtype: int64

In [16]:
df.dtypes

patient_id                               object
slope_of_peak_exercise_st_segment         int64
thal                                     object
resting_blood_pressure                    int64
chest_pain_type                           int64
num_major_vessels                         int64
fasting_blood_sugar_gt_120_mg_per_dl      int64
resting_ekg_results                       int64
serum_cholesterol_mg_per_dl               int64
oldpeak_eq_st_depression                float64
sex                                       int64
age                                       int64
max_heart_rate_achieved                   int64
exercise_induced_angina                   int64
heart_disease_present                     int64
dtype: object

In [17]:
# Preprocessing
df['thal'].unique()

array(['normal', 'reversible_defect', 'fixed_defect'], dtype=object)

In [18]:
# Preprocessing
# dropping unnecessary columns
df=df.drop('patient_id',axis=1)

In [19]:
df.columns

Index(['slope_of_peak_exercise_st_segment', 'thal', 'resting_blood_pressure',
       'chest_pain_type', 'num_major_vessels',
       'fasting_blood_sugar_gt_120_mg_per_dl', 'resting_ekg_results',
       'serum_cholesterol_mg_per_dl', 'oldpeak_eq_st_depression', 'sex', 'age',
       'max_heart_rate_achieved', 'exercise_induced_angina',
       'heart_disease_present'],
      dtype='object')

In [20]:
# One Hot Encoding thal
df=pd.get_dummies(df,columns=['thal'],drop_first=True)

df.head()

In [21]:
print(df.head())

   slope_of_peak_exercise_st_segment  resting_blood_pressure  chest_pain_type  \
0                                  1                     128                2
1                                  2                     110                3
2                                  1                     125                4
3                                  1                     152                4
4                                  3                     178                1

   num_major_vessels  fasting_blood_sugar_gt_120_mg_per_dl  \
0                  0                                     0
1                  0                                     0
2                  3                                     0
3                  0                                     0
4                  0                                     0

   resting_ekg_results  serum_cholesterol_mg_per_dl  oldpeak_eq_st_depression  \
0                    2                          308                       0.0
1                    0                          214                       1.6
2                    2                          304                       0.0
3                    0                          223                       0.0
4                    2                          270                       4.2

   sex  age  max_heart_rate_achieved  exercise_induced_angina  \
0    1   45                      170                        0
1    0   54                      158                        0
2    1   77                      162                        1
3    1   40                      181                        0
4    1   59                      145                        0

   heart_disease_present  thal_normal  thal_reversible_defect
0                      0         True                   False
1                      0         True                   False
2                      1         True                   False
3                      1        False                    True
4                      0        False                    True

In [22]:
df[['thal_normal', 'thal_reversible_defect']] = df[['thal_normal', 'thal_reversible_defect']].astype(int)

In [23]:
df.head()

,slope_of_peak_exercise_st_segment,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina,heart_disease_present,thal_normal,thal_reversible_defect
0,1,128,2,0,0,2,308,0.0,1,45,170,0,0,1,0
1,2,110,3,0,0,0,214,1.6,0,54,158,0,0,1,0
2,1,125,4,3,0,2,304,0.0,1,77,162,1,1,1,0
3,1,152,4,0,0,0,223,0.0,1,40,181,0,1,0,1
4,3,178,1,0,0,2,270,4.2,1,59,145,0,0,0,1

In [24]:
# Separating Fearures and Target
x=df.drop('heart_disease_present',axis=1)

y=df['heart_disease_present']

In [25]:
x.shape

(180, 14)

In [26]:
y.shape

(180,)